services:

  frontend:
    container_name: cerebro-frontend
    build:
      context: "./Diseno/IyR/Frontend"
      dockerfile: Dockerfile
    ports:
      - "4173:80"
    restart: unless-stopped
    depends_on:
      - cerebro-api

  cerebro-api:
    container_name: cerebro-api
    build:
      context: "./MVP-BackEnd/Contenedor1/api"
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - "./MVP-BackEnd/Contenedor1/api/.env"
    restart: unless-stopped

  contenedor2:
    container_name: cerebro-contenedor2
    build:
      context: "./MVP-BackEnd/Contenedor2"
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - "./MVP-BackEnd/Contenedor2/.env"
    restart: unless-stopped